"""Generate patent DOCX via docx-js. Dispatched from write_docx.py when spec type is 'patent'.

Supports CNIPA (Chinese) and USPTO/EPO/PCT (English) jurisdictions.
Patent types: invention, utility_model, design.
"""

import os
import sys

# Reuse helpers and constants from write_docx
try:
    from write_docx import _escape_js_string, A4_WIDTH, A4_HEIGHT, DEFAULT_MARGIN
except ImportError:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from write_docx import _escape_js_string, A4_WIDTH, A4_HEIGHT, DEFAULT_MARGIN


def generate_patent_js(spec: dict, output_path: str, spec_dir: str) -> str:
    patent = spec.get("patent", {})
    jurisdiction = patent.get("jurisdiction", "cn")
    patent_type = patent.get("patent_type", "invention")

    if jurisdiction == "cn":
        if patent_type == "design":
            return _gen_cn_design_js(spec, output_path, spec_dir)
        return _gen_cn_invention_js(spec, output_path, spec_dir, patent_type)
    else:
        if patent_type == "design":
            return _gen_en_design_js(spec, output_path, spec_dir)
        return _gen_en_invention_js(spec, output_path, spec_dir)


# ── shared JS helpers ──────────────────────────────────────────────

def _emit_imports(lines: list[str]) -> None:
    lines.append("// Auto-generated by docx-write/gen_patent.py")
    lines.append("const fs = require('fs');")
    lines.append("const path = require('path');")
    lines.append("const {")
    lines.append("  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,")
    lines.append("  AlignmentType, HeadingLevel, LevelFormat,")
    lines.append("  BorderStyle, WidthType, ShadingType, PageBreak, ImageRun,")
    lines.append("} = require('docx');")
    lines.append("")


def _emit_styles(lines: list[str], body_font: str, heading_font: str,
                 font_size: int = 24) -> None:
    heading_specs = [
        ("Heading1", "Heading 1", 32, 240),
        ("Heading2", "Heading 2", 28, 180),
        ("Heading3", "Heading 3", 26, 120),
    ]
    lines.append("  styles: {")
    lines.append("    default: {")
    lines.append("      document: {")
    lines.append(f"        run: {{ font: {_escape_js_string(body_font)}, "
                 f"size: {font_size}, color: \"000000\" }},")
    lines.append("      },")
    lines.append("    },")
    lines.append("    paragraphStyles: [")
    for idx, (h_id, h_name, h_size, h_space) in enumerate(heading_specs):
        lines.append("      {")
        lines.append(f'        id: "{h_id}",')
        lines.append(f'        name: "{h_name}",')
        lines.append('        basedOn: "Normal",')
        lines.append('        next: "Normal",')
        lines.append("        quickFormat: true,")
        lines.append(f"        run: {{ size: {h_size}, bold: true, "
                     f"font: {_escape_js_string(heading_font)} }},")
        lines.append(f"        paragraph: {{ spacing: {{ before: {h_space}, "
                     f"after: {h_space // 2} }}, outlineLevel: {idx} }},")
        lines.append("      },")
    lines.append("    ],")
    lines.append("  },")


def _emit_numbering(lines: list[str]) -> None:
    lines.append("  numbering: {")
    lines.append("    config: [")
    lines.append("      {")
    lines.append('        reference: "claims",')
    lines.append("        levels: [{")
    lines.append("          level: 0,")
    lines.append('          format: LevelFormat.DECIMAL,')
    lines.append('          text: "%1.",')
    lines.append("          alignment: AlignmentType.LEFT,")
    lines.append("          style: { paragraph: { indent: { left: 720, hanging: 360 } } },")
    lines.append("        }],")
    lines.append("      },")
    lines.append("      {")
    lines.append('        reference: "bullets",')
    lines.append("        levels: [{")
    lines.append("          level: 0,")
    lines.append('          format: LevelFormat.BULLET,')
    lines.append('          text: "•",')
    lines.append("          alignment: AlignmentType.LEFT,")
    lines.append("          style: { paragraph: { indent: { left: 720, hanging: 360 } } },")
    lines.append("        }],")
    lines.append("      },")
    lines.append("    ],")
    lines.append("  },")


def _emit_page_setup(lines: list[str], spec: dict) -> int:
    page = spec.get("page", {})
    pw = page.get("width", A4_WIDTH)
    ph = page.get("height", A4_HEIGHT)
    margins = page.get("margins", {
        "top": DEFAULT_MARGIN, "bottom": DEFAULT_MARGIN,
        "left": DEFAULT_MARGIN, "right": DEFAULT_MARGIN,
    })
    cw = pw - margins.get("left", 0) - margins.get("right", 0)

    lines.append("  sections: [{")
    lines.append("    properties: {")
    lines.append("      page: {")
    lines.append(f"        size: {{ width: {pw}, height: {ph} }},")
    lines.append(f"        margin: {{ top: {margins['top']}, bottom: {margins['bottom']}, "
                 f"left: {margins['left']}, right: {margins['right']} }},")
    lines.append("      },")
    lines.append("    },")
    lines.append("    children: [")
    return cw


def _emit_doc_footer(lines: list[str], output_path: str) -> None:
    lines.append("    ],")
    lines.append("  }],")
    lines.append("});")
    lines.append("")
    lines.append(f"Packer.toBuffer(doc).then(buf => "
                 f"fs.writeFileSync({_escape_js_string(output_path)}, buf));")
    lines.append("console.log('Patent DOCX written to ' + "
                 f"{_escape_js_string(output_path)});")


def _emit_claim_paragraph(lines: list[str], claim_text: str, font: str) -> None:
    lines.append("      new Paragraph({")
    lines.append('        numbering: { reference: "claims", level: 0 },')
    lines.append("        spacing: { after: 80 },")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(claim_text)}, "
                 f"font: {_escape_js_string(font)}, size: 24 }})],")
    lines.append("      }),")


def _emit_body_paragraph(lines: list[str], text: str, font: str,
                         first_line_indent: bool = True) -> None:
    indent = ", indent: { firstLine: 480 }" if first_line_indent else ""
    lines.append("      new Paragraph({")
    lines.append(f"        spacing: {{ after: 120 }}{indent},")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(text)}, "
                 f"font: {_escape_js_string(font)}, size: 24 }})],")
    lines.append("      }),")


def _emit_section_heading(lines: list[str], heading: str, level: int,
                          heading_font: str) -> None:
    heading_map = {1: "HeadingLevel.HEADING_1", 2: "HeadingLevel.HEADING_2",
                   3: "HeadingLevel.HEADING_3"}
    hl = heading_map.get(level, "HeadingLevel.HEADING_1")
    lines.append("      new Paragraph({")
    lines.append(f"        heading: {hl},")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(heading)}, "
                 f"font: {_escape_js_string(heading_font)}, bold: true }})],")
    lines.append("      }),")


def _emit_image_block(lines: list[str], src: str, caption: str,
                      font: str, spec_dir: str, width_px: int = 400) -> None:
    img_path = os.path.join(spec_dir, src) if not os.path.isabs(src) else src
    ext = os.path.splitext(src)[1].lstrip(".").lower()
    img_type = {"jpg": "jpg", "jpeg": "jpeg", "png": "png",
                "gif": "gif", "bmp": "bmp", "svg": "svg"}.get(ext, "png")
    h_px = int(width_px * 0.75)

    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { before: 200, after: 100 },")
    lines.append("        children: [new ImageRun({")
    lines.append(f'          type: "{img_type}",')
    lines.append(f"          data: fs.readFileSync({_escape_js_string(img_path)}),")
    lines.append(f"          transformation: {{ width: {width_px}, height: {h_px} }},")
    lines.append(f"          altText: {{ title: {_escape_js_string(caption)}, "
                 f"description: {_escape_js_string(caption)} }},")
    lines.append("        })],")
    lines.append("      }),")
    if caption:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 200 },")
        lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(caption)}, "
                     f"font: {_escape_js_string(font)}, size: 20, color: \"555555\" }})],")
        lines.append("      }),")


# ── CN invention / utility model ───────────────────────────────────

def _gen_cn_invention_js(spec: dict, output_path: str, spec_dir: str,
                         patent_type: str) -> str:
    patent = spec.get("patent", {})
    heading_font = "黑体"
    body_font = "宋体"
    lines = []
    _emit_imports(lines)
    lines.append("const doc = new Document({")
    _emit_styles(lines, body_font, heading_font)
    _emit_numbering(lines)
    cw = _emit_page_setup(lines, spec)

    # Title
    title = patent.get("title", "")
    lines.append("      // ===== TITLE =====")
    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { after: 200 },")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(title)}, "
                 f"font: {_escape_js_string(heading_font)}, size: 32, bold: true }})],")
    lines.append("      }),")

    # Applicant / Inventor info
    applicant = patent.get("applicant", "")
    inventors = patent.get("inventors", [])
    inv_names = ", ".join(i.get("name", "") for i in inventors)
    if applicant or inv_names:
        lines.append("      // ===== APPLICANT / INVENTOR =====")
        if applicant:
            lines.append("      new Paragraph({")
            lines.append("        alignment: AlignmentType.CENTER,")
            lines.append("        spacing: { after: 60 },")
            lines.append(f"        children: [new TextRun({{ text: \"申请人：{applicant}\", "
                         f"font: {_escape_js_string(body_font)}, size: 24 }})],")
            lines.append("      }),")
        if inv_names:
            lines.append("      new Paragraph({")
            lines.append("        alignment: AlignmentType.CENTER,")
            lines.append("        spacing: { after: 200 },")
            lines.append(f"        children: [new TextRun({{ text: \"发明人：{inv_names}\", "
                         f"font: {_escape_js_string(body_font)}, size: 24 }})],")
            lines.append("      }),")

    # Claims
    claims = patent.get("claims", [])
    if claims:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== 权利要求书 =====")
        _emit_section_heading(lines, "权利要求书", 1, heading_font)
        for claim_text in claims:
            _emit_claim_paragraph(lines, claim_text, body_font)

    # Description body (sections from spec)
    sections = spec.get("sections", [])
    drawings = patent.get("drawings", [])
    for sec in sections:
        heading = sec.get("heading", "")
        level = sec.get("level", 1)
        _emit_section_heading(lines, heading, level, heading_font)

        for item in sec.get("content", []):
            tp = item.get("type", "paragraph")
            if tp == "paragraph":
                _emit_body_paragraph(lines, item.get("text", ""), body_font)
            elif tp == "image":
                _emit_image_block(lines, item.get("src", ""),
                                  item.get("caption", ""), body_font, spec_dir,
                                  item.get("width", 400))

    # Drawings appendix
    if drawings:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== 说明书附图 =====")
        _emit_section_heading(lines, "说明书附图", 1, heading_font)
        for dwg in drawings:
            _emit_image_block(lines, dwg.get("src", ""),
                              dwg.get("caption", dwg.get("ref", "")),
                              body_font, spec_dir, dwg.get("width", 400))

    # Abstract
    abstract = patent.get("abstract", "")
    if abstract:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== 说明书摘要 =====")
        _emit_section_heading(lines, "说明书摘要", 1, heading_font)
        _emit_body_paragraph(lines, abstract, body_font, first_line_indent=False)

    _emit_doc_footer(lines, output_path)
    return "\n".join(lines)


# ── CN design patent ───────────────────────────────────────────────

def _gen_cn_design_js(spec: dict, output_path: str, spec_dir: str) -> str:
    patent = spec.get("patent", {})
    heading_font = "黑体"
    body_font = "宋体"
    lines = []
    _emit_imports(lines)
    lines.append("const doc = new Document({")
    _emit_styles(lines, body_font, heading_font)
    _emit_numbering(lines)
    _emit_page_setup(lines, spec)

    # Product name
    product_name = patent.get("product_name", patent.get("title", ""))
    lines.append("      // ===== 外观设计 =====")
    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { after: 200 },")
    lines.append(f"        children: [new TextRun({{ text: \"外观设计专利\", "
                 f"font: {_escape_js_string(heading_font)}, size: 32, bold: true }})],")
    lines.append("      }),")
    if product_name:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 200 },")
        lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(product_name)}, "
                     f"font: {_escape_js_string(body_font)}, size: 28, bold: true }})],")
        lines.append("      }),")

    # Brief explanation sections
    for field, label in [("product_purpose", "一、本外观设计产品的用途"),
                          ("design_features", "二、本外观设计的设计要点"),
                          ("primary_view", "三、最能表明设计要点的图片或照片")]:
        val = patent.get(field, "")
        if val:
            lines.append("      new Paragraph({")
            lines.append("        spacing: { before: 200, after: 80 },")
            lines.append(f"        children: [new TextRun({{ text: \"{label}：\", "
                         f"font: {_escape_js_string(heading_font)}, size: 24, bold: true }})],")
            lines.append("      }),")
            _emit_body_paragraph(lines, val, body_font, first_line_indent=False)

    # Views grid (2 columns)
    views = patent.get("views", [])
    if views:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== 视图 =====")
        _emit_section_heading(lines, "外观设计视图", 1, heading_font)

        for i in range(0, len(views), 2):
            row_views = views[i:i + 2]
            lines.append("      new Table({")
            lines.append("        width: { size: 100, type: WidthType.PERCENTAGE },")
            lines.append("        rows: [")
            lines.append("          new TableRow({")
            lines.append("            children: [")
            for v in row_views:
                v_src = v.get("src", "")
                v_name = v.get("name", "")
                img_path = os.path.join(spec_dir, v_src) if not os.path.isabs(v_src) else v_src
                ext = os.path.splitext(v_src)[1].lstrip(".").lower()
                img_type = {"jpg": "jpg", "jpeg": "jpeg", "png": "png",
                            "gif": "gif", "bmp": "bmp", "svg": "svg"}.get(ext, "png")
                lines.append("              new TableCell({")
                lines.append("                borders: { top: { style: BorderStyle.SINGLE, "
                             "size: 1, color: \"CCCCCC\" }, bottom: { style: BorderStyle.SINGLE, "
                             "size: 1, color: \"CCCCCC\" }, left: { style: BorderStyle.SINGLE, "
                             "size: 1, color: \"CCCCCC\" }, right: { style: BorderStyle.SINGLE, "
                             "size: 1, color: \"CCCCCC\" } },")
                lines.append("                margins: { top: 80, bottom: 80, left: 80, right: 80 },")
                lines.append("                children: [")
                lines.append("                  new Paragraph({")
                lines.append("                    alignment: AlignmentType.CENTER,")
                lines.append(f"                    children: [new TextRun({{ text: "
                             f"{_escape_js_string(v_name)}, font: {_escape_js_string(body_font)}, "
                             f"size: 20, bold: true }})],")
                lines.append("                  }),")
                if v_src:
                    lines.append("                  new Paragraph({")
                    lines.append("                    alignment: AlignmentType.CENTER,")
                    lines.append("                    spacing: { before: 60 },")
                    lines.append("                    children: [new ImageRun({")
                    lines.append(f'                      type: "{img_type}",')
                    lines.append(f"                      data: fs.readFileSync("
                                 f"{_escape_js_string(img_path)}),")
                    lines.append(f"                      transformation: {{ width: 220, "
                                 f"height: 165 }},")
                    lines.append(f"                      altText: {{ title: "
                                 f"{_escape_js_string(v_name)} }},")
                    lines.append("                    })],")
                    lines.append("                  }),")
                lines.append("                ],")
                lines.append("              }),")
            # Pad empty cell if odd number of views
            if len(row_views) == 1:
                lines.append("              new TableCell({")
                lines.append("                borders: { top: { style: BorderStyle.NONE }, "
                             "bottom: { style: BorderStyle.NONE }, "
                             "left: { style: BorderStyle.NONE }, "
                             "right: { style: BorderStyle.NONE } },")
                lines.append("                children: [],")
                lines.append("              }),")
            lines.append("            ],")
            lines.append("          }),")
            lines.append("        ],")
            lines.append("      }),")

    _emit_doc_footer(lines, output_path)
    return "\n".join(lines)


# ── EN invention patent (USPTO / EPO / PCT) ────────────────────────

def _gen_en_invention_js(spec: dict, output_path: str, spec_dir: str) -> str:
    patent = spec.get("patent", {})
    heading_font = "Times New Roman"
    body_font = "Times New Roman"
    lines = []
    _emit_imports(lines)
    lines.append("const doc = new Document({")
    _emit_styles(lines, body_font, heading_font)
    _emit_numbering(lines)
    _emit_page_setup(lines, spec)

    # Title
    title = patent.get("title", "")
    lines.append("      // ===== TITLE =====")
    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { after: 200 },")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(title)}, "
                 f"font: {_escape_js_string(heading_font)}, size: 32, bold: true }})],")
    lines.append("      }),")

    # Inventors / Applicant
    applicant = patent.get("applicant", "")
    inventors = patent.get("inventors", [])
    inv_names = ", ".join(i.get("name", "") for i in inventors)
    if inv_names:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 60 },")
        lines.append(f"        children: [new TextRun({{ text: \"Inventors: {inv_names}\", "
                     f"font: {_escape_js_string(body_font)}, size: 24 }})],")
        lines.append("      }),")
    if applicant:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 200 },")
        lines.append(f"        children: [new TextRun({{ text: \"Applicant: {applicant}\", "
                     f"font: {_escape_js_string(body_font)}, size: 24 }})],")
        lines.append("      }),")

    # Cross-reference to related apps
    related = patent.get("related_applications", "")
    if related:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        _emit_section_heading(lines, "CROSS-REFERENCE TO RELATED APPLICATIONS", 1,
                              heading_font)
        _emit_body_paragraph(lines, related, body_font)

    # Abstract
    abstract = patent.get("abstract", "")
    if abstract:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== ABSTRACT =====")
        _emit_section_heading(lines, "ABSTRACT OF THE DISCLOSURE", 1, heading_font)
        _emit_body_paragraph(lines, abstract, body_font, first_line_indent=False)

    # Body sections
    sections = spec.get("sections", [])
    for sec in sections:
        heading = sec.get("heading", "")
        level = sec.get("level", 1)
        if level == 1:
            lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        _emit_section_heading(lines, heading, level, heading_font)

        for item in sec.get("content", []):
            tp = item.get("type", "paragraph")
            if tp == "paragraph":
                _emit_body_paragraph(lines, item.get("text", ""), body_font)
            elif tp == "image":
                _emit_image_block(lines, item.get("src", ""),
                                  item.get("caption", ""), body_font, spec_dir,
                                  item.get("width", 400))

    # Claims section
    claims = patent.get("claims", [])
    if claims:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== CLAIMS =====")
        _emit_section_heading(lines, "What is claimed is:", 1, heading_font)
        for claim_text in claims:
            _emit_claim_paragraph(lines, claim_text, body_font)

    # Drawings
    drawings = patent.get("drawings", [])
    if drawings:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        lines.append("      // ===== DRAWINGS =====")
        _emit_section_heading(lines, "BRIEF DESCRIPTION OF THE DRAWINGS", 1, heading_font)
        for dwg in drawings:
            _emit_image_block(lines, dwg.get("src", ""),
                              dwg.get("caption", dwg.get("ref", "")),
                              body_font, spec_dir, dwg.get("width", 400))

    _emit_doc_footer(lines, output_path)
    return "\n".join(lines)


# ── EN design patent (USPTO) ───────────────────────────────────────

def _gen_en_design_js(spec: dict, output_path: str, spec_dir: str) -> str:
    patent = spec.get("patent", {})
    heading_font = "Times New Roman"
    body_font = "Times New Roman"
    lines = []
    _emit_imports(lines)
    lines.append("const doc = new Document({")
    _emit_styles(lines, body_font, heading_font)
    _emit_numbering(lines)
    _emit_page_setup(lines, spec)

    title = patent.get("title", patent.get("product_name", ""))
    lines.append("      // ===== DESIGN PATENT =====")
    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { after: 200 },")
    lines.append(f"        children: [new TextRun({{ text: {_escape_js_string(title)}, "
                 f"font: {_escape_js_string(heading_font)}, size: 32, bold: true }})],")
    lines.append("      }),")

    # Inventors
    inventors = patent.get("inventors", [])
    inv_names = ", ".join(i.get("name", "") for i in inventors)
    if inv_names:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 200 },")
        lines.append(f"        children: [new TextRun({{ text: \"Inventors: {inv_names}\", "
                     f"font: {_escape_js_string(body_font)}, size: 24 }})],")
        lines.append("      }),")

    # FIG. 1 description
    fig_desc = patent.get("figure_description", "")
    if fig_desc:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        _emit_section_heading(lines, "DESCRIPTION OF THE FIGURES", 1, heading_font)
        _emit_body_paragraph(lines, fig_desc, body_font)

    # Single claim
    design_claim = patent.get("claim", "")
    if design_claim:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        _emit_section_heading(lines, "CLAIM", 1, heading_font)
        _emit_claim_paragraph(lines, design_claim, body_font)

    # Figures
    drawings = patent.get("drawings", [])
    if drawings:
        lines.append("      new Paragraph({ children: [new PageBreak()] }),")
        _emit_section_heading(lines, "DRAWINGS", 1, heading_font)
        for dwg in drawings:
            _emit_image_block(lines, dwg.get("src", ""),
                              dwg.get("caption", dwg.get("ref", "")),
                              body_font, spec_dir, dwg.get("width", 450))

    _emit_doc_footer(lines, output_path)
    return "\n".join(lines)
