#!/usr/bin/env python3
"""Generate a DOCX from a structured YAML/JSON specification.

Uses docx-js (Node.js npm package) to create the document.
Generates a temporary JS script and executes it via subprocess.

Usage:
    python scripts/write_docx.py paper.yaml --output paper.docx
    python scripts/write_docx.py paper.yaml -c 北交模板 -p 论文名 -v 1
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

import yaml

# A4 page size in DXA
A4_WIDTH = 11906
A4_HEIGHT = 16838
DEFAULT_MARGIN = 1440  # 1 inch in DXA
DEFAULT_FONT = "Times New Roman"
DEFAULT_FONT_SIZE = 24  # half-points, 24 = 12pt


def load_spec(path: str) -> dict:
    """Load a YAML or JSON specification file."""
    with open(path, "r", encoding="utf-8") as f:
        if path.endswith((".yaml", ".yml")):
            return yaml.safe_load(f)
        return json.load(f)


def _escape_js_string(text: str) -> str:
    """Escape a string for safe embedding in JavaScript template literal."""
    return json.dumps(text, ensure_ascii=False)


def _validate_docx(path: str) -> bool:
    """Basic validation: check the file is a well-formed ZIP (DOCX is a ZIP)."""
    try:
        with zipfile.ZipFile(path, "r") as zf:
            bad = zf.testzip()
            if bad:
                print(f"  Warning: corrupt entry in DOCX: {bad}", file=sys.stderr)
                return False
            names = zf.namelist()
            if "[Content_Types].xml" not in names:
                print("  Warning: missing [Content_Types].xml", file=sys.stderr)
                return False
        return True
    except (zipfile.BadZipFile, OSError) as e:
        print(f"  Validation failed: {e}", file=sys.stderr)
        return False


def generate_js(spec: dict, output_path: str, spec_dir: str) -> str:
    """Generate a complete Node.js script using docx-js to create the DOCX."""
    page = spec.get("page", {})
    page_width = page.get("width", A4_WIDTH)
    page_height = page.get("height", A4_HEIGHT)
    margins = page.get("margins", {
        "top": DEFAULT_MARGIN,
        "bottom": DEFAULT_MARGIN,
        "left": DEFAULT_MARGIN,
        "right": DEFAULT_MARGIN,
    })
    content_width = page_width - margins.get("left", 0) - margins.get("right", 0)

    style = spec.get("style", {})
    font = style.get("default_font", DEFAULT_FONT)
    font_size = style.get("default_font_size", DEFAULT_FONT_SIZE)
    font_color = style.get("default_font_color", "000000")

    lines = []
    lines.append("// Auto-generated by docx-write/write_docx.py")
    lines.append("const fs = require('fs');")
    lines.append("const path = require('path');")
    lines.append("const {")
    lines.append("  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,")
    lines.append("  Header, Footer, AlignmentType, HeadingLevel, LevelFormat,")
    lines.append(
        "  BorderStyle, WidthType, ShadingType, PageBreak, PageNumber,"
    )
    lines.append(
        "  ExternalHyperlink, ImageRun, TabStopType, TabStopPosition"
    )
    lines.append("} = require('docx');")
    lines.append("")
    lines.append("const doc = new Document({")

    # Styles
    lines.append("  styles: {")
    lines.append("    default: {")
    lines.append("      document: {")
    lines.append(f'        run: {{ font: {_escape_js_string(font)}, size: {font_size}, color: "{font_color}" }},')
    lines.append("      },")
    lines.append("    },")
    lines.append("    paragraphStyles: [")
    heading_styles = [
        ("Heading1", "Heading 1", 32, 240),
        ("Heading2", "Heading 2", 28, 180),
        ("Heading3", "Heading 3", 26, 120),
        ("Heading4", "Heading 4", 24, 120),
    ]
    for idx, (h_id, h_name, h_size, h_space) in enumerate(heading_styles):
        lines.append("      {")
        lines.append(f'        id: "{h_id}",')
        lines.append(f'        name: "{h_name}",')
        lines.append('        basedOn: "Normal",')
        lines.append('        next: "Normal",')
        lines.append("        quickFormat: true,")
        lines.append(f"        run: {{ size: {h_size}, bold: true, font: {_escape_js_string(font)} }},")
        lines.append(
            f"        paragraph: {{ spacing: {{ before: {h_space}, after: {h_space // 2} }}, outlineLevel: {idx} }},"
        )
        lines.append("      },")
    lines.append("    ],")
    lines.append("  },")

    # Numbering config (for lists)
    lines.append("  numbering: {")
    lines.append("    config: [")
    lines.append("      {")
    lines.append('        reference: "bullets",')
    lines.append("        levels: [{")
    lines.append("          level: 0,")
    lines.append('          format: LevelFormat.BULLET,')
    lines.append('          text: "•",')
    lines.append("          alignment: AlignmentType.LEFT,")
    lines.append(
        "          style: { paragraph: { indent: { left: 720, hanging: 360 } } },"
    )
    lines.append("        }],")
    lines.append("      },")
    lines.append("      {")
    lines.append('        reference: "numbers",')
    lines.append("        levels: [{")
    lines.append("          level: 0,")
    lines.append('          format: LevelFormat.DECIMAL,')
    lines.append('          text: "%1.",')
    lines.append("          alignment: AlignmentType.LEFT,")
    lines.append(
        "          style: { paragraph: { indent: { left: 720, hanging: 360 } } },"
    )
    lines.append("        }],")
    lines.append("      },")
    lines.append("    ],")
    lines.append("  },")

    # Section content
    lines.append("  sections: [{")
    lines.append("    properties: {")
    lines.append("      page: {")
    lines.append(f"        size: {{ width: {page_width}, height: {page_height} }},")
    lines.append(
        f"        margin: {{ top: {margins['top']}, bottom: {margins['bottom']}, "
        f"left: {margins['left']}, right: {margins['right']} }},"
    )
    lines.append("      },")
    lines.append("    },")

    # Header
    lines.append("    headers: {")
    lines.append("      default: new Header({")
    lines.append("        children: [new Paragraph({")
    title_en = spec.get("title", {})
    title_text = title_en.get("en", "") or title_en.get("cn", "") or ""
    lines.append(
        f"          alignment: AlignmentType.CENTER,"
    )
    lines.append(
        f"          children: [new TextRun({{ text: {_escape_js_string(title_text)}, "
        f"font: {_escape_js_string(font)}, size: 18, color: \"888888\" }})],"
    )
    lines.append("        })],")
    lines.append("      }),")
    lines.append("    },")

    # Footer with page numbers
    lines.append("    footers: {")
    lines.append("      default: new Footer({")
    lines.append("        children: [new Paragraph({")
    lines.append("          alignment: AlignmentType.CENTER,")
    lines.append("          children: [")
    lines.append(
        "            new TextRun({ text: \"— \", font: "
        + _escape_js_string(font)
        + ", size: 18, color: \"888888\" }),"
    )
    lines.append("            new TextRun({ children: [PageNumber.CURRENT],")
    lines.append(
        f"              font: {_escape_js_string(font)}, size: 18, color: \"888888\" }}),"
    )
    lines.append(
        "            new TextRun({ text: \" —\", font: "
        + _escape_js_string(font)
        + ", size: 18, color: \"888888\" }),"
    )
    lines.append("          ],")
    lines.append("        })],")
    lines.append("      }),")
    lines.append("    },")

    # Body children
    lines.append("    children: [")
    lines.append("      // ===== TITLE =====")
    lines += _gen_title(spec, font)
    lines.append("      // ===== AUTHORS =====")
    lines += _gen_authors(spec, font)
    lines.append("      // ===== ABSTRACT =====")
    lines += _gen_abstract(spec, font)
    lines.append("      // ===== KEYWORDS =====")
    lines += _gen_keywords(spec, font)
    lines.append("      // ===== BODY SECTIONS =====")
    lines += _gen_sections(spec, font, content_width, spec_dir)
    lines.append("      // ===== REFERENCES =====")
    lines += _gen_references(spec, font)

    lines.append("    ],")
    lines.append("  }],")
    lines.append("});")
    lines.append("")
    lines.append(
        f"Packer.toBuffer(doc).then(buf => fs.writeFileSync({_escape_js_string(output_path)}, buf));"
    )

    return "\n".join(lines)


def _gen_title(spec: dict, font: str) -> list[str]:
    """Generate the title paragraph(s) in JS."""
    lines = []
    title = spec.get("title", {})
    cn_title = title.get("cn", "")
    en_title = title.get("en", "")

    lines.append("      // Title paragraph(s)")
    if cn_title:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 120 },")
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(cn_title)}, "
            f"font: {_escape_js_string(font)}, size: 36, bold: true }})],"
        )
        lines.append("      }),")
    if en_title:
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        en_size = 36 if not cn_title else 28
        lines.append("        spacing: { after: 200 },")
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(en_title)}, "
            f"font: {_escape_js_string(font)}, size: {en_size}, bold: true }})],"
        )
        lines.append("      }),")

    return lines


def _gen_authors(spec: dict, font: str) -> list[str]:
    """Generate author paragraph(s)."""
    lines = []
    authors = spec.get("authors", [])
    if not authors:
        return lines

    name_parts = [a.get("name", "") for a in authors]
    name_line = ", ".join(name_parts)
    lines.append("      new Paragraph({")
    lines.append("        alignment: AlignmentType.CENTER,")
    lines.append("        spacing: { after: 120 },")
    lines.append(
        f"        children: [new TextRun({{ text: {_escape_js_string(name_line)}, "
        f"font: {_escape_js_string(font)}, size: 24 }})],"
    )
    lines.append("      }),")

    affiliations = {}
    for author in authors:
        aff = author.get("affiliation", "")
        if aff and aff not in affiliations:
            affiliations[aff] = len(affiliations) + 1

    for aff, num in affiliations.items():
        lines.append("      new Paragraph({")
        lines.append("        alignment: AlignmentType.CENTER,")
        lines.append("        spacing: { after: 80 },")
        label = f"{num}. {aff}"
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(label)}, "
            f"font: {_escape_js_string(font)}, size: 20, color: \"555555\" }})],"
        )
        lines.append("      }),")

    return lines


def _gen_abstract(spec: dict, font: str) -> list[str]:
    """Generate abstract section."""
    lines = []
    abstract = spec.get("abstract", {})
    if not abstract:
        return lines

    cn_abstract = abstract.get("cn", "")
    en_abstract = abstract.get("en", "")

    if cn_abstract:
        lines.append("      new Paragraph({")
        lines.append("        heading: HeadingLevel.HEADING_1,")
        lines.append("        children: [new TextRun({ text: \"摘要\",")
        lines.append(
            f"          font: {_escape_js_string(font)}, size: 32, bold: true }})],"
        )
        lines.append("      }),")
        lines.append("      new Paragraph({")
        lines.append("        spacing: { after: 200 },")
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(cn_abstract)}, "
            f"font: {_escape_js_string(font)}, size: 24 }})],"
        )
        lines.append("      }),")

    if en_abstract:
        lines.append("      new Paragraph({")
        lines.append("        heading: HeadingLevel.HEADING_1,")
        lines.append("        children: [new TextRun({ text: \"Abstract\",")
        lines.append(
            f"          font: {_escape_js_string(font)}, size: 32, bold: true }})],"
        )
        lines.append("      }),")
        lines.append("      new Paragraph({")
        lines.append("        spacing: { after: 200 },")
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(en_abstract)}, "
            f"font: {_escape_js_string(font)}, size: 24 }})],"
        )
        lines.append("      }),")

    return lines


def _gen_keywords(spec: dict, font: str) -> list[str]:
    """Generate keywords section."""
    lines = []
    keywords = spec.get("keywords", {})
    if not keywords:
        return lines

    cn_kw = keywords.get("cn", [])
    en_kw = keywords.get("en", [])

    if cn_kw:
        kw_text = "关键词：" + "；".join(cn_kw)
        lines.append("      new Paragraph({")
        lines.append("        spacing: { after: 200 },")
        lines.append("        children: [")
        lines.append(
            f"          new TextRun({{ text: {_escape_js_string(kw_text)}, "
            f"font: {_escape_js_string(font)}, size: 24, bold: false }}),"
        )
        lines.append("        ],")
        lines.append("      }),")

    if en_kw:
        kw_text = "Keywords: " + "; ".join(en_kw)
        lines.append("      new Paragraph({")
        lines.append("        spacing: { after: 200 },")
        lines.append("        children: [")
        lines.append(
            f"          new TextRun({{ text: {_escape_js_string(kw_text)}, "
            f"font: {_escape_js_string(font)}, size: 24, bold: false }}),"
        )
        lines.append("        ],")
        lines.append("      }),")

    return lines


def _gen_sections(spec: dict, font: str, content_width: int, spec_dir: str) -> list[str]:
    """Generate body sections from spec."""
    lines = []
    sections = spec.get("sections", [])

    heading_map = {
        1: "HeadingLevel.HEADING_1",
        2: "HeadingLevel.HEADING_2",
        3: "HeadingLevel.HEADING_3",
        4: "HeadingLevel.HEADING_4",
    }

    for sec_idx, section in enumerate(sections):
        heading = section.get("heading", "")
        level = section.get("level", 1)
        heading_level = heading_map.get(level, "HeadingLevel.HEADING_1")
        content_items = section.get("content", [])

        if heading:
            if level == 1 and sec_idx > 0:
                lines.append(
                    "      new Paragraph({ children: [new PageBreak()] }),"
                )

            lines.append("      new Paragraph({")
            lines.append(f"        heading: {heading_level},")
            lines.append(
                f"        children: [new TextRun({{ text: {_escape_js_string(heading)}, "
                f"font: {_escape_js_string(font)}, bold: true }})],"
            )
            lines.append("      }),")

        for item in content_items:
            item_type = item.get("type", "paragraph")

            if item_type == "paragraph":
                text = item.get("text", "")
                lines.append("      new Paragraph({")
                lines.append("        spacing: { after: 120 },")
                lines.append(
                    f"        children: [new TextRun({{ text: {_escape_js_string(text)}, "
                    f"font: {_escape_js_string(font)}, size: 24 }})],"
                )
                lines.append("      }),")

            elif item_type == "image":
                src = item.get("src", "")
                caption = item.get("caption", "")
                width_px = item.get("width", 400)

                img_path = os.path.join(spec_dir, src) if not os.path.isabs(src) else src

                lines.append("      new Paragraph({")
                lines.append("        alignment: AlignmentType.CENTER,")
                lines.append("        spacing: { before: 200, after: 100 },")
                ext = os.path.splitext(src)[1].lstrip(".").lower()
                img_type = {"jpg": "jpg", "jpeg": "jpeg", "png": "png", "gif": "gif", "bmp": "bmp", "svg": "svg"}.get(ext, "png")
                lines.append("        children: [new ImageRun({")
                lines.append(f'          type: "{img_type}",')
                lines.append(
                    f"          data: fs.readFileSync({_escape_js_string(img_path)}),"
                )
                lines.append(
                    f"          transformation: {{ width: {width_px}, height: {int(width_px * 0.75)} }},"
                )
                lines.append(f"          altText: {{ title: {_escape_js_string(caption)}, description: {_escape_js_string(caption)}, name: {_escape_js_string(caption)} }},")
                lines.append("        })],")
                lines.append("      }),")

                if caption:
                    lines.append("      new Paragraph({")
                    lines.append("        alignment: AlignmentType.CENTER,")
                    lines.append("        spacing: { after: 200 },")
                    lines.append(
                        f"        children: [new TextRun({{ text: {_escape_js_string(caption)}, "
                        f"font: {_escape_js_string(font)}, size: 20, color: \"555555\" }})],"
                    )
                    lines.append("      }),")

            elif item_type == "table":
                caption = item.get("caption", "")
                columns = item.get("columns", [])
                rows = item.get("rows", [])
                num_cols = len(columns)
                if num_cols == 0:
                    continue

                col_width_base = content_width // num_cols
                col_widths = [col_width_base] * num_cols
                remainder = content_width - col_width_base * num_cols
                col_widths[-1] += remainder
                col_widths_str = ", ".join(str(w) for w in col_widths)

                if caption:
                    lines.append("      new Paragraph({")
                    lines.append("        alignment: AlignmentType.CENTER,")
                    lines.append("        spacing: { before: 200, after: 100 },")
                    lines.append(
                        f"        children: [new TextRun({{ text: {_escape_js_string(caption)}, "
                        f"font: {_escape_js_string(font)}, size: 20, bold: true, color: \"555555\" }})],"
                    )
                    lines.append("      }),")

                # Table
                lines.append("      new Table({")
                lines.append(
                    f"        width: {{ size: {content_width}, type: WidthType.DXA }},"
                )
                lines.append(
                    f"        columnWidths: [{col_widths_str}],"
                )
                lines.append("        rows: [")

                # Header row
                lines.append("          new TableRow({")
                lines.append("            tableHeader: true,")
                lines.append("            children: [")
                border = "BorderStyle.SINGLE"
                for idx, col_name in enumerate(columns):
                    cw = col_widths[idx]
                    lines.append("              new TableCell({")
                    lines.append(
                        f"                borders: {{ top: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, bottom: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, left: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, right: {{ style: {border}, size: 1, color: \"CCCCCC\" }} }},"
                    )
                    lines.append(
                        f"                width: {{ size: {cw}, type: WidthType.DXA }},"
                    )
                    lines.append(
                        "                shading: { fill: \"EEEEEE\", type: ShadingType.CLEAR },"
                    )
                    lines.append(
                        "                margins: { top: 80, bottom: 80, left: 120, right: 120 },"
                    )
                    lines.append("                children: [new Paragraph({")
                    lines.append(
                        f"                  children: [new TextRun({{ text: {_escape_js_string(col_name)}, "
                        f"font: {_escape_js_string(font)}, size: 22, bold: true }})],"
                    )
                    lines.append("                })],")
                    lines.append("              }),")
                lines.append("            ],")
                lines.append("          }),")

                # Data rows
                for row in rows:
                    lines.append("          new TableRow({")
                    lines.append("            children: [")
                    for idx, cell_text in enumerate(row[:num_cols]):
                        cw = col_widths[idx]
                        lines.append("              new TableCell({")
                        lines.append(
                            f"                borders: {{ top: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, bottom: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, left: {{ style: {border}, size: 1, color: \"CCCCCC\" }}, right: {{ style: {border}, size: 1, color: \"CCCCCC\" }} }},"
                        )
                        lines.append(
                            f"                width: {{ size: {cw}, type: WidthType.DXA }},"
                        )
                        lines.append(
                            "                margins: { top: 80, bottom: 80, left: 120, right: 120 },"
                        )
                        lines.append("                children: [new Paragraph({")
                        lines.append(
                            f"                  children: [new TextRun({{ text: {_escape_js_string(str(cell_text))}, "
                            f"font: {_escape_js_string(font)}, size: 22 }})],"
                        )
                        lines.append("                })],")
                        lines.append("              }),")
                    lines.append("            ],")
                    lines.append("          }),")

                lines.append("        ],")
                lines.append("      }),")

            elif item_type == "list":
                ordered = item.get("ordered", False)
                ref = "numbers" if ordered else "bullets"
                list_items = item.get("items", [])

                for li in list_items:
                    lines.append("      new Paragraph({")
                    lines.append(
                        f'        numbering: {{ reference: "{ref}", level: 0 }},'
                    )
                    lines.append("        spacing: { after: 60 },")
                    lines.append(
                        f"        children: [new TextRun({{ text: {_escape_js_string(li)}, "
                        f"font: {_escape_js_string(font)}, size: 24 }})],"
                    )
                    lines.append("      }),")

    return lines


def _gen_references(spec: dict, font: str) -> list[str]:
    """Generate references section."""
    lines = []
    references = spec.get("references", [])
    if not references:
        return lines

    lines.append(
        "      new Paragraph({ children: [new PageBreak()] }),"
    )
    lines.append("      new Paragraph({")
    lines.append("        heading: HeadingLevel.HEADING_1,")
    lines.append("        children: [new TextRun({ text: \"参考文献\",")
    lines.append(
        f"          font: {_escape_js_string(font)}, size: 32, bold: true }})],"
    )
    lines.append("      }),")

    for ref in references:
        text = ref.get("text", "")
        lines.append("      new Paragraph({")
        lines.append("        spacing: { after: 60 },")
        lines.append(
            f"        children: [new TextRun({{ text: {_escape_js_string(text)}, "
            f"font: {_escape_js_string(font)}, size: 20 }})],"
        )
        lines.append("      }),")

    return lines


def resolve_output_path(spec: dict, input_path: str, args: argparse.Namespace) -> str:
    """Determine output DOCX path from CLI args or spec metadata."""
    if args.output:
        return args.output

    meta = spec.get("meta", {})
    paper_name = args.paper or meta.get("paper_name", "")
    category = args.category or meta.get("category", "")
    version = args.version or meta.get("version", 1)

    if category and paper_name:
        # Resolve relative to current working directory (not script location)
        out_dir = Path.cwd() / "outputs" / paper_name / category / f"v{version}"
        out_dir.mkdir(parents=True, exist_ok=True)
        return str(out_dir / f"{paper_name}-generated.docx")

    input_path_obj = Path(input_path)
    return str(input_path_obj.with_suffix(".docx"))


def main():
    parser = argparse.ArgumentParser(
        description="Generate a DOCX from a structured YAML/JSON specification."
    )
    parser.add_argument(
        "input_file", help="YAML or JSON specification file"
    )
    parser.add_argument(
        "--output", "-o", help="Output DOCX path (default: derived from input name)"
    )
    parser.add_argument(
        "--category", "-c",
        help="Template category for output path (e.g. 北交模板)",
    )
    parser.add_argument(
        "--paper", "-p",
        help="Paper name for output path",
    )
    parser.add_argument(
        "--version", "-v", type=int,
        help="Version number for output path",
    )
    parser.add_argument(
        "--skip-validate", action="store_true",
        help="Skip DOCX validation",
    )
    parser.add_argument(
        "--verbose", "-V", action="store_true",
        help="Show generated JS script content",
    )
    args = parser.parse_args()

    # Load spec
    spec_path = Path(args.input_file).resolve()
    if not spec_path.exists():
        print(f"Spec file not found: {args.input_file}", file=sys.stderr)
        sys.exit(1)

    spec = load_spec(str(spec_path))
    spec_dir = str(spec_path.parent)
    output_path = resolve_output_path(spec, args.input_file, args)

    print(f"Generating DOCX from: {args.input_file}")
    print(f"Output: {output_path}")

    # Generate JS script
    js_code = generate_js(spec, str(Path(output_path).resolve()), spec_dir)

    if args.verbose:
        print("\n--- Generated JS ---")
        print(js_code)
        print("--- End JS ---\n")

    # Write and execute JS
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".js", delete=False, encoding="utf-8"
    )
    try:
        tmp.write(js_code)
        tmp.close()

        env = os.environ.copy()
        npm_root = subprocess.run(
            ["npm", "root", "-g"], capture_output=True, text=True
        ).stdout.strip()
        if "NODE_PATH" in env:
            env["NODE_PATH"] = npm_root + os.pathsep + env["NODE_PATH"]
        else:
            env["NODE_PATH"] = npm_root
        result = subprocess.run(
            ["node", tmp.name],
            capture_output=True,
            text=True,
            env=env,
        )
        if result.returncode != 0:
            print(f"Node.js generation failed:\n{result.stderr}", file=sys.stderr)
            sys.exit(1)
        if result.stdout:
            print(result.stdout)
    finally:
        os.unlink(tmp.name)

    # Validate
    if not args.skip_validate:
        print("Validating output...")
        if _validate_docx(output_path):
            print("Validation passed.")
        else:
            print("(Use --skip-validate to bypass)", file=sys.stderr)

    print(f"\nGenerated: {output_path}")


if __name__ == "__main__":
    main()
